### ISSUE TITLE
create UT

### ISSUE THREAD

**Issue by romani** [checkstyle/metadata-gen#31]
UT should take java file (copy of XxxxxxxCheck.java from checkstyle repo)
generate xml in memory or temp file and compare with existing xml file.

All problematic javadocs from checkstyle repo should be fixed to be easy to parse or in predictable  structure to reliably parse files.

each found problem should result in new UT creation.

**Comment by gaurabdg** [comment]
> UT should take java file (copy of XxxxxxxCheck.java from checkstyle repo)
> generate xml in memory or temp file and compare with existing xml file.

@romani But this will not ensure proper metadata property validation, since both the moduleDetails object in memory and XML file contents are same.

There is one approach I though of:
While automatically editing javadocs, I dumped property values such as type, parent, violation messages into a txt. I can do this for all required properties such as default value also. Then in UTs we can compare the moduleDetails object created from scraping the javadoc and compare to that present in the txt dumps. This will ensure data consistency between generated XML files and the actual xdoc values(since xdocs are highly structured)

**Comment by romani** [comment]
>ensure proper metadata property validation

What do you mean by this ?
We do not need to validate, javadoc us source of truth ( validated by some other code). We just parse it and take text values from it and place in xml format

**Comment by gaurabdg** [comment]
@romani I was thinking of crosschecking all generated metadata files with xdocs whether they contain proper data or not. This will avoid failures like the one you pointed out today.

**Comment by strkkk** [comment]
@gaurabdg As first step we can check basic things - violation keys are present, description is not empty, etc.

>we have to manually check each generated meta file for valid data

If file passed smoke tests I mentioned above, we assume it is correct. If later we find some errors in javadoc, javadoc can be corrected.
I do not like crosscheck with xdocs since xdocs can be generated later based on metadata.

**Comment by gaurabdg** [comment]
Sure, noted.

**Comment by romani** [comment]
Please focus on satisfying plugins first, we need to complete files generation for plugins first

**Comment by gaurabdg** [comment]
@romani Please close this
